### ISSUE TITLE
The json config file exist but not read by application

### ISSUE THREAD

**Issue by magloui** [Dashbrd/CalendarSyncplus#53]
The json config file is saved on location <Os Drive>:\Users\<User Name>\AppData\Roaming\CalendarSyncPlus,  but after restart the application not take into account the configuration.

In version v1.4.18111.01-alpha portable installation

**Comment by LemarinelNet** [comment]
Same for me...

**Comment by ankeshdave** [comment]
We have reproduced the issue in our staging environment, we'll release a fix ASAP
