### ISSUE TITLE
Must install with .NET 4.6.1, but doesn't work with newer revs

### ISSUE THREAD

**Issue by modelmanjohn** [Dashbrd/CalendarSyncplus#54]
I have a new install of win10, and it has .Net compact framework 2.0 SP2 and 3.5. When I try to install calendarsyncplus, it fails because it wants .Net 4.6.1. At first I didn't think I had .Net installed, so I grabbed 4.6.1 to install, but it halts and says that a newer rev is already installed. So either I have to uninstall what I have and reinstall 4.6.1 (not sure I can do that with win10), or does this app not recognize that my system already has a rev above it installed (of course, what I have may not be backwards compatible to 4.6.1, but I don't know how to check that).

**Comment by aauren** [comment]
I have a similar issue with the installer incorrectly identifying what version of .NET I have installed. In my case, I actually have 4.6.1 installed and it still seems to think that it isn't installed. I went to the link and ensured that I had 4.6.1 installed, and I do so it only has the option to repair the existing installation. Even doing that and rebooting the installer still doesn't recognize it.

**Comment by lisztomania** [comment]
Stumbled right into this issue too. Anyone found a way to fix it or bypass it?

**Comment by ankeshdave** [comment]
We are looking into this , will fix this ASAP.
