### ISSUE TITLE
1.5.18275.02-alpha triggers Symantec WS.Reputation.1

### ISSUE THREAD

**Issue by nomisunrider** [Dashbrd/CalendarSyncplus#61]
The CalendarSyncPlus.exe for version 1.5.18275.02-alpha triggers this Symantec Antivirus alert.  
Version 1.4.18105.02-alpha does not.

https://www.symantec.com/security-center/writeup/2010-051308-1854-99?vid=4294919973

**Comment by ankeshdave** [comment]
I think is a false positive,
I wanted to submit it. But it's asking me a bunch of questions which i dont have information about, could you get me more information about this.
Symantec is asking these questions

https://submit.symantec.com/false_positive/

**Comment by nomisunrider** [comment]
SEP no longer flags it, so the false positive must have been fixed in a newer definition.  Please close this.

Thank you
